#!/usr/bin/env ruby

$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))


puts $:

require 'eventmachine'
require 'optparse'
#require 'em-synchrony'
require 'time'
require 'yajl'


require 'runner'
require 'server'
require 'log/console'

HGT::Runner.new(ARGV).run