#!/usr/bin/env ruby

$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))

require 'eventmachine'
require 'optparse'
require 'em-http-request'
require 'time'
require 'yajl'
require 'fb_graph'


require 'runner'
require 'server'
require 'log/console'

HGT::Runner.new(ARGV).run